# Target architecture build matrix for EGS_W1
include:
  - board: nice_nano_v2   
    shield: egs_left
  - board: nice_nano_v2   
    shield: egs_right
  - board: nice_nano_v2
    shield: tester_pro_micro