# Copyright (c) 2026 The EGS_W1 Project
# SPDX-License-Identifier: MIT

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable deep sleep state for maximum battery longevity
CONFIG_ZMK_SLEEP=y

# 5 minutes of inactivity before entering a soft idle state (low power radio)
CONFIG_ZMK_IDLE_TIMEOUT=300000

# 15 minutes of inactivity before entering a hardware deep sleep state
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Natively monitor and report battery percentages to the host OS
CONFIG_ZMK_BATTERY_REPORTING=y

# Allow the Left (Central) half to fetch and display the Right side's battery level
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_DISPLAY=y
CONFIG_ZMK_POINTING=y